// <auto-generated />
namespace SelfHost.Migrations.ScopeConfiguration
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class v2_0_0 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v2_0_0));
        
        string IMigrationMetadata.Id
        {
            get { return "201504070215165_v2_0_0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
