// <auto-generated />
namespace SelfHost.Migrations.ScopeConfiguration
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class v2_4_0 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v2_4_0));
        
        string IMigrationMetadata.Id
        {
            get { return "201601182228505_v2_4_0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
